<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[{
    "_meta": {
        "success": true,
        "code": 201,
        "message": "A resource was successfully created in response to a POST request. The Location header contains the URL pointing to the newly created resource.",
        "rateLimit": {
            "limit": 30,
            "remaining": 29,
            "reset": 2
        }
    },
    "result": {
        "id": "22645",
        "first_name": "Brian",
        "last_name": "Ratke",
        "gender": "male",
        "dob": null,
        "email": "AutoNF9HLCJY33@test.com",
        "phone": null,
        "website": null,
        "address": null,
        "status": "active",
        "_links": {
            "self": {
                "href": "https://gorest.co.in/public-api/users/22645"
            },
            "edit": {
                "href": "https://gorest.co.in/public-api/users/22645"
            },
            "avatar": {
                "href": null
            }
        }
    }
}]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="4417" started-at="2020-05-12T19:35:12 COT" finished-at="2020-05-12T19:35:16 COT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4417" started-at="2020-05-12T19:35:12 COT" finished-at="2020-05-12T19:35:16 COT">
      <class name="com.ab.apitest.tests.UserTest">
        <test-method status="FAIL" signature="createUser()[pri:0, instance:com.ab.apitest.tests.UserTest@5f282abb]" name="createUser" duration-ms="2785" started-at="2020-05-12T19:35:12 COT" description="User can create a user" finished-at="2020-05-12T19:35:14 COT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<201> but was:<302>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<201> but was:<302>
at org.junit.Assert.fail(Assert.java:88)
at org.junit.Assert.failNotEquals(Assert.java:834)
at org.junit.Assert.assertEquals(Assert.java:645)
at org.junit.Assert.assertEquals(Assert.java:631)
at com.ab.apitest.tests.UserTest.createUser(UserTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[{
    "_meta": {
        "success": true,
        "code": 201,
        "message": "A resource was successfully created in response to a POST request. The Location header contains the URL pointing to the newly created resource.",
        "rateLimit": {
            "limit": 30,
            "remaining": 29,
            "reset": 2
        }
    },
    "result": {
        "id": "22645",
        "first_name": "Brian",
        "last_name": "Ratke",
        "gender": "male",
        "dob": null,
        "email": "AutoNF9HLCJY33@test.com",
        "phone": null,
        "website": null,
        "address": null,
        "status": "active",
        "_links": {
            "self": {
                "href": "https://gorest.co.in/public-api/users/22645"
            },
            "edit": {
                "href": "https://gorest.co.in/public-api/users/22645"
            },
            "avatar": {
                "href": null
            }
        }
    }
}]]>
            </line>
          </reporter-output>
        </test-method> <!-- createUser -->
        <test-method status="PASS" signature="getUser()[pri:0, instance:com.ab.apitest.tests.UserTest@5f282abb]" name="getUser" duration-ms="1606" started-at="2020-05-12T19:35:14 COT" description="User can get the users" finished-at="2020-05-12T19:35:16 COT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getUser -->
      </class> <!-- com.ab.apitest.tests.UserTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
